/*
 * ziv_app.h - host-portable core of the QEMU boot app (ladder rung 1).
 *
 * docs/QEMU_SIMULATION_LADDER.md: this core is the part worth proving. It
 * owns the real sequencer (haptic_out), emits the machine-parseable HAP
 * timeline lines from the sequencer's OWN event stream (the real firmware's
 * testimony, not a parallel model), chains the scripted boot demo, and
 * exposes the console actions the UART protocol dispatches to.
 *
 * It compiles unchanged in two places (same rule as haptic_out itself):
 *   - under ESP-IDF, linked from main.c on the emulated chip (QEMU), and
 *   - on the host bench, driven by host_demo.c with a virtual clock -
 *     which is where its timeline is asserted end to end.
 *
 * Host-portable: no ESP-IDF types in this layer.
 */
#ifndef ZIV_APP_H
#define ZIV_APP_H

#include <stdbool.h>
#include <stdint.h>
#include "drv2605_i2c.h"
#include "haptic_out.h"
#include "ziv_demo_sequence.h"   /* generated: the scripted boot demo's single source */

/*
 * HAP line format (one line per sequencer event):
 *
 *   HAP <at_ms> START <mode>
 *   HAP <at_ms> BUZZ <mode> <payload> <mask_hex> <buzz_ms> <gap_ms> <seq>
 *   HAP <at_ms> END
 *
 *   at_ms    monotonic ms (esp_timer on band, virtual clock on bench)
 *   mode     MARK | PATTERN | WORD | PREFIX
 *   payload  PATTERN: pattern id from the timing spec ("double-tap", ...),
 *            MARK: mark id ("ziv", ...), WORD: the letters, PREFIX: tail id
 *            ("message" | "reminder" | "error")
 *   mask_hex two hex digits, which dot motors are up during the buzz
 *            (00 for attention/lifecycle patterns - they are whole-device
 *            ticks; cells carry the letter bitmask)
 *   gap_ms   the silence AFTER this buzz (belongs to the buzzing beat)
 *
 * Silence is derivable (BUZZ end -> next BUZZ start), so gaps are asserted
 * from at_ms deltas, never logged separately. tools/qemu_timeline.py
 * (rung 2) diffs this log against the bench log.
 */
typedef void (*ziv_hap_sink)(void *ctx, const char *line);

typedef struct {
    haptic_out haptic;   /* the real sequencer */
    ziv_hap_sink sink;   /* HAP line sink (NULL = silent) */
    void *sink_ctx;
    bool demo_done;      /* scripted boot demo finished */
    int demo_stage;      /* index into k_demo_sequence[] */
} ziv_app;

void ziv_app_init(ziv_app *app, drv2605_bus *bus, ziv_hap_sink sink, void *sink_ctx);

/*
 * Advance the timeline. now_ms is the monotonic time in ms; returns the
 * time of the next state change, now_ms when the caller should call again
 * immediately (START / a chained play), 0 when idle. Emits HAP lines.
 */
uint32_t ziv_app_step(ziv_app *app, uint32_t now_ms);

/*
 * The scripted boot demo (rung 2's fixture) is defined once as machine-
 * readable data and derived into both the app's runtime table and the host
 * bench's expected fixture:
 *   ziv_demo_sequence.h  - generated single source (demo stage table +
 *                            the 27-line HAP fixture), regenerated by
 *                            tools/haptic_timing.py --write from the same
 *                            timing vocab the rest of the project uses.
 *   k_demo_sequence[]    - the stage table the app chains at runtime
 *                          (re-exported from ziv_demo_sequence.h).
 *   k_demo_expected[]    - the HAP fixture host_demo.c asserts against
 *                          (re-exported from ziv_demo_sequence.h); derived
 *                          from k_demo_sequence[] + the generated timing
 *                          tables so reordering/extending the demo cannot
 *                          silently desync the fixture from the demo it
 *                          describes.
 *
 * Both are used by host_demo.c (rung 2) and by the QEMU boot
 * (app_main.c - rung 1). The ladder doc points at this table as the
 * machine-checkable description of the demo.
 */

void ziv_app_run_demo(ziv_app *app);

/* The demo stage table + derived HAP fixture are re-exported from the
 * generated header. */
extern const int k_demo_stage_count;
extern const demo_stage_t k_demo_sequence[];
extern const char *const k_demo_expected[];
extern const int k_demo_expected_count;

/*
 * Console actions - thin wrappers that also work as the app API for the
 * fake-relay tests later. They return a haptic_err_t (HAPTIC_OK = 0).
 */
int ziv_app_play_pattern(ziv_app *app, int pat_idx);
int ziv_app_play_mark(ziv_app *app, int mark_idx);
int ziv_app_play_word(ziv_app *app, const char *word);
int ziv_app_play_prefix(ziv_app *app, int tail_idx);
void ziv_app_stop(ziv_app *app);

/*
 * Name -> index lookups for the console protocol (exact ids from the
 * generated timing spec: "double-tap", "end-of-message", "ziv", ...).
 * Return -1 when the name is unknown. The index tables live next to the
 * generated enums in ziv_app.c and follow their order (HAPTIC_PAT_ then
 * HAPTIC_MARK_ then HAPTIC_TAIL_); the timing checker
 * (tools/haptic_timing.py) holds spec <-> header in sync, and rung 2
 * holds the HAP names to these tables.
 */
int ziv_pattern_index(const char *id);
int ziv_mark_index(const char *id);
int ziv_tail_index(const char *id);

#endif /* ZIV_APP_H */
